export type PairType = 'forex' | 'crypto' | 'commodity';

export interface PairInfo {
  symbol: string;
  displayName: string;
  type: PairType;
  pipSize: number;          // e.g., 0.0001 for EUR/USD, 0.01 for JPY pairs
  pipValuePerLot: number;   // pip value in USD per standard lot (100k units)
  decimalPlaces: number;
  typicalSpread: number;    // in pips
  contractSize: number;     // 100000 for forex, 1 for crypto
  baseCurrency: string;
  quoteCurrency: string;
}

export const FOREX_PAIRS: PairInfo[] = [
  {
    symbol: 'EURUSD',
    displayName: 'EUR/USD',
    type: 'forex',
    pipSize: 0.0001,
    pipValuePerLot: 10,
    decimalPlaces: 5,
    typicalSpread: 1.2,
    contractSize: 100000,
    baseCurrency: 'EUR',
    quoteCurrency: 'USD',
  },
  {
    symbol: 'GBPUSD',
    displayName: 'GBP/USD',
    type: 'forex',
    pipSize: 0.0001,
    pipValuePerLot: 10,
    decimalPlaces: 5,
    typicalSpread: 1.5,
    contractSize: 100000,
    baseCurrency: 'GBP',
    quoteCurrency: 'USD',
  },
  {
    symbol: 'USDJPY',
    displayName: 'USD/JPY',
    type: 'forex',
    pipSize: 0.01,
    pipValuePerLot: 6.67,
    decimalPlaces: 3,
    typicalSpread: 1.0,
    contractSize: 100000,
    baseCurrency: 'USD',
    quoteCurrency: 'JPY',
  },
  {
    symbol: 'AUDUSD',
    displayName: 'AUD/USD',
    type: 'forex',
    pipSize: 0.0001,
    pipValuePerLot: 10,
    decimalPlaces: 5,
    typicalSpread: 1.4,
    contractSize: 100000,
    baseCurrency: 'AUD',
    quoteCurrency: 'USD',
  },
  {
    symbol: 'USDCAD',
    displayName: 'USD/CAD',
    type: 'forex',
    pipSize: 0.0001,
    pipValuePerLot: 7.52,
    decimalPlaces: 5,
    typicalSpread: 1.8,
    contractSize: 100000,
    baseCurrency: 'USD',
    quoteCurrency: 'CAD',
  },
  {
    symbol: 'EURGBP',
    displayName: 'EUR/GBP',
    type: 'forex',
    pipSize: 0.0001,
    pipValuePerLot: 12.65,
    decimalPlaces: 5,
    typicalSpread: 1.5,
    contractSize: 100000,
    baseCurrency: 'EUR',
    quoteCurrency: 'GBP',
  },
  {
    symbol: 'GBPJPY',
    displayName: 'GBP/JPY',
    type: 'forex',
    pipSize: 0.01,
    pipValuePerLot: 6.67,
    decimalPlaces: 3,
    typicalSpread: 2.5,
    contractSize: 100000,
    baseCurrency: 'GBP',
    quoteCurrency: 'JPY',
  },
  {
    symbol: 'EURJPY',
    displayName: 'EUR/JPY',
    type: 'forex',
    pipSize: 0.01,
    pipValuePerLot: 6.67,
    decimalPlaces: 3,
    typicalSpread: 1.8,
    contractSize: 100000,
    baseCurrency: 'EUR',
    quoteCurrency: 'JPY',
  },
  {
    symbol: 'NZDUSD',
    displayName: 'NZD/USD',
    type: 'forex',
    pipSize: 0.0001,
    pipValuePerLot: 10,
    decimalPlaces: 5,
    typicalSpread: 2.0,
    contractSize: 100000,
    baseCurrency: 'NZD',
    quoteCurrency: 'USD',
  },
  {
    symbol: 'USDCHF',
    displayName: 'USD/CHF',
    type: 'forex',
    pipSize: 0.0001,
    pipValuePerLot: 11.24,
    decimalPlaces: 5,
    typicalSpread: 1.6,
    contractSize: 100000,
    baseCurrency: 'USD',
    quoteCurrency: 'CHF',
  },
  {
    symbol: 'EURCHF',
    displayName: 'EUR/CHF',
    type: 'forex',
    pipSize: 0.0001,
    pipValuePerLot: 11.24,
    decimalPlaces: 5,
    typicalSpread: 1.7,
    contractSize: 100000,
    baseCurrency: 'EUR',
    quoteCurrency: 'CHF',
  },
  {
    symbol: 'EURCAD',
    displayName: 'EUR/CAD',
    type: 'forex',
    pipSize: 0.0001,
    pipValuePerLot: 7.52,
    decimalPlaces: 5,
    typicalSpread: 2.0,
    contractSize: 100000,
    baseCurrency: 'EUR',
    quoteCurrency: 'CAD',
  },
  {
    symbol: 'AUDJPY',
    displayName: 'AUD/JPY',
    type: 'forex',
    pipSize: 0.01,
    pipValuePerLot: 6.67,
    decimalPlaces: 3,
    typicalSpread: 1.6,
    contractSize: 100000,
    baseCurrency: 'AUD',
    quoteCurrency: 'JPY',
  },
  {
    symbol: 'CADJPY',
    displayName: 'CAD/JPY',
    type: 'forex',
    pipSize: 0.01,
    pipValuePerLot: 6.67,
    decimalPlaces: 3,
    typicalSpread: 1.8,
    contractSize: 100000,
    baseCurrency: 'CAD',
    quoteCurrency: 'JPY',
  },
  {
    symbol: 'CHFJPY',
    displayName: 'CHF/JPY',
    type: 'forex',
    pipSize: 0.01,
    pipValuePerLot: 6.67,
    decimalPlaces: 3,
    typicalSpread: 2.1,
    contractSize: 100000,
    baseCurrency: 'CHF',
    quoteCurrency: 'JPY',
  },
];

export const CRYPTO_PAIRS: PairInfo[] = [
  {
    symbol: 'BTCUSD',
    displayName: 'BTC/USD',
    type: 'crypto',
    pipSize: 0.01,
    pipValuePerLot: 0.01,
    decimalPlaces: 2,
    typicalSpread: 30,
    contractSize: 1,
    baseCurrency: 'BTC',
    quoteCurrency: 'USD',
  },
  {
    symbol: 'ETHUSD',
    displayName: 'ETH/USD',
    type: 'crypto',
    pipSize: 0.01,
    pipValuePerLot: 0.01,
    decimalPlaces: 2,
    typicalSpread: 5,
    contractSize: 1,
    baseCurrency: 'ETH',
    quoteCurrency: 'USD',
  },
  {
    symbol: 'SOLUSD',
    displayName: 'SOL/USD',
    type: 'crypto',
    pipSize: 0.01,
    pipValuePerLot: 0.01,
    decimalPlaces: 2,
    typicalSpread: 0.5,
    contractSize: 1,
    baseCurrency: 'SOL',
    quoteCurrency: 'USD',
  },
  {
    symbol: 'XRPUSD',
    displayName: 'XRP/USD',
    type: 'crypto',
    pipSize: 0.0001,
    pipValuePerLot: 0.0001,
    decimalPlaces: 4,
    typicalSpread: 0.005,
    contractSize: 1,
    baseCurrency: 'XRP',
    quoteCurrency: 'USD',
  },
  {
    symbol: 'ADAUSD',
    displayName: 'ADA/USD',
    type: 'crypto',
    pipSize: 0.0001,
    pipValuePerLot: 0.0001,
    decimalPlaces: 4,
    typicalSpread: 0.003,
    contractSize: 1,
    baseCurrency: 'ADA',
    quoteCurrency: 'USD',
  },
  {
    symbol: 'DOGEUSD',
    displayName: 'DOGE/USD',
    type: 'crypto',
    pipSize: 0.00001,
    pipValuePerLot: 0.00001,
    decimalPlaces: 5,
    typicalSpread: 0.001,
    contractSize: 1,
    baseCurrency: 'DOGE',
    quoteCurrency: 'USD',
  },
  {
    symbol: 'AVAXUSD',
    displayName: 'AVAX/USD',
    type: 'crypto',
    pipSize: 0.01,
    pipValuePerLot: 0.01,
    decimalPlaces: 2,
    typicalSpread: 0.3,
    contractSize: 1,
    baseCurrency: 'AVAX',
    quoteCurrency: 'USD',
  },
  {
    symbol: 'LINKUSD',
    displayName: 'LINK/USD',
    type: 'crypto',
    pipSize: 0.01,
    pipValuePerLot: 0.01,
    decimalPlaces: 2,
    typicalSpread: 0.1,
    contractSize: 1,
    baseCurrency: 'LINK',
    quoteCurrency: 'USD',
  },
  {
    symbol: 'BNBUSD',
    displayName: 'BNB/USD',
    type: 'crypto',
    pipSize: 0.01,
    pipValuePerLot: 0.01,
    decimalPlaces: 2,
    typicalSpread: 0.6,
    contractSize: 1,
    baseCurrency: 'BNB',
    quoteCurrency: 'USD',
  },
  {
    symbol: 'LTCUSD',
    displayName: 'LTC/USD',
    type: 'crypto',
    pipSize: 0.01,
    pipValuePerLot: 0.01,
    decimalPlaces: 2,
    typicalSpread: 0.25,
    contractSize: 1,
    baseCurrency: 'LTC',
    quoteCurrency: 'USD',
  },
  {
    symbol: 'DOTUSD',
    displayName: 'DOT/USD',
    type: 'crypto',
    pipSize: 0.001,
    pipValuePerLot: 0.001,
    decimalPlaces: 3,
    typicalSpread: 0.03,
    contractSize: 1,
    baseCurrency: 'DOT',
    quoteCurrency: 'USD',
  },
  {
    symbol: 'MATICUSD',
    displayName: 'MATIC/USD',
    type: 'crypto',
    pipSize: 0.0001,
    pipValuePerLot: 0.0001,
    decimalPlaces: 4,
    typicalSpread: 0.004,
    contractSize: 1,
    baseCurrency: 'MATIC',
    quoteCurrency: 'USD',
  },
  {
    symbol: 'TRXUSD',
    displayName: 'TRX/USD',
    type: 'crypto',
    pipSize: 0.00001,
    pipValuePerLot: 0.00001,
    decimalPlaces: 5,
    typicalSpread: 0.0004,
    contractSize: 1,
    baseCurrency: 'TRX',
    quoteCurrency: 'USD',
  },
  {
    symbol: 'BCHUSD',
    displayName: 'BCH/USD',
    type: 'crypto',
    pipSize: 0.01,
    pipValuePerLot: 0.01,
    decimalPlaces: 2,
    typicalSpread: 0.8,
    contractSize: 1,
    baseCurrency: 'BCH',
    quoteCurrency: 'USD',
  },
];

export const COMMODITY_PAIRS: PairInfo[] = [
  {
    symbol: 'XAUUSD',
    displayName: 'XAU/USD',
    type: 'commodity',
    pipSize: 0.01,
    pipValuePerLot: 1,
    decimalPlaces: 2,
    typicalSpread: 30,
    contractSize: 100,
    baseCurrency: 'XAU',
    quoteCurrency: 'USD',
  },
  {
    symbol: 'XAGUSD',
    displayName: 'XAG/USD',
    type: 'commodity',
    pipSize: 0.001,
    pipValuePerLot: 5,
    decimalPlaces: 3,
    typicalSpread: 2.5,
    contractSize: 5000,
    baseCurrency: 'XAG',
    quoteCurrency: 'USD',
  },
  {
    symbol: 'WTIUSD',
    displayName: 'WTI/USD',
    type: 'commodity',
    pipSize: 0.01,
    pipValuePerLot: 10,
    decimalPlaces: 2,
    typicalSpread: 3,
    contractSize: 1000,
    baseCurrency: 'OIL',
    quoteCurrency: 'USD',
  },
  {
    symbol: 'BRENTUSD',
    displayName: 'BRENT/USD',
    type: 'commodity',
    pipSize: 0.01,
    pipValuePerLot: 10,
    decimalPlaces: 2,
    typicalSpread: 3.2,
    contractSize: 1000,
    baseCurrency: 'BRENT',
    quoteCurrency: 'USD',
  },
  {
    symbol: 'NGASUSD',
    displayName: 'NGAS/USD',
    type: 'commodity',
    pipSize: 0.001,
    pipValuePerLot: 10,
    decimalPlaces: 3,
    typicalSpread: 4.5,
    contractSize: 10000,
    baseCurrency: 'NGAS',
    quoteCurrency: 'USD',
  },
];

export const ALL_PAIRS: PairInfo[] = [...FOREX_PAIRS, ...CRYPTO_PAIRS, ...COMMODITY_PAIRS];

export function getPairBySymbol(symbol: string): PairInfo | undefined {
  return ALL_PAIRS.find((p) => p.symbol === symbol);
}
